//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_proyecto.Views {

    public partial class VerUsuarios {
        protected global::System.Web.UI.WebControls.TextBox txtBuscarUsuario;
        protected global::System.Web.UI.WebControls.Button btnBuscarUsuario;
        protected global::System.Web.UI.WebControls.Button btnLimpiarUsuario;
        protected global::System.Web.UI.WebControls.GridView gvUsuarios;
        protected global::System.Web.UI.WebControls.HiddenField hdnAccion;
        protected global::System.Web.UI.WebControls.HiddenField hdnIdUsuario;
        protected global::System.Web.UI.WebControls.Button btnAccionOculto;
        protected global::System.Web.UI.WebControls.TextBox txtNombreUsuario;
        protected global::System.Web.UI.WebControls.TextBox txtEmailUsuario;
        protected global::System.Web.UI.WebControls.DropDownList ddlRolUsuario;
        protected global::System.Web.UI.WebControls.CheckBox chkActivo;
        protected global::System.Web.UI.WebControls.Button btnGuardarUsuario;
    }
}
